insert into news_item (id, title, url) values (1, 'CNN', 'http://www.cnn.com/');
insert into news_item (id, title, url) values (2, 'FOX News', 'http://www.foxnews.com/');
insert into news_item (id, title, url) values (3, 'BBC News', 'http://news.bbc.co.uk/2/hi/help/rss/default.stm');
insert into news_item (id, title, url) values (4, 'Malayala Manorama ', 'http://www.manoramaonline.com/');
insert into news_item (id, title, url) values (5, 'Deepika', 'http://www.deepika.com/');
insert into news_item (id, title, url) values (6, 'Marunadan Malayali', 'http://www.marunadanmalayali.com/');
insert into news_item (id, title, url) values (7, 'Irish Malayali', 'http://www.irishmalayali.com/');
insert into news_item (id, title, url) values (8, 'Rose Malayalam', 'http://www.rosemalayalam.com/');
insert into news_item (id, title, url) values (9, 'Irish Independent', 'http://www.independent.ie');
insert into news_item (id, title, url) values (10, 'Irish Times', 'http://www.irishtimes.com/');
